###################################################
#                                                 #
# Home Assistant Main Configuration File          #
#                                                 #
################################################### 
#
# https://github.com/CiquattroFPV/Homeassistant-Example-Config
#

homeassistant:
  name: !secret name
  temperature_unit: C
  time_zone: !secret timezone
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: metric
  elevation: 0
  customize: !include_dir_merge_named customizations
  whitelist_external_dirs:
    - /tmp
    # - /home/pi/.homeassistant/captures

###################################################
#                                                 #
#                   IFTTT                         #
#                                                 #
###################################################

ifttt:
  key: !secret ifttt_key

####################################################
#                                                  #
#                     Enables                      #
#                                                  #
####################################################
config:
logger:
  default: warn
  logs:
    homeassistant.components.device_tracker: warn
    homeassistant.components.camera: error
    homeassistant.components.automation: warn
    homeassistant.components.light: warn
    homeassistant.components.sensor: warn
    homeassistant.components.scene: warn
    homeassistant.components.switch: warn
    homeassistant.components.ifttt: warn
history:
  exclude:
    domains:
      - automation
      - weblink
      - updater
    entities:
      - sun.sun   # Don't record sun data
      - sensor.last_boot
      - sensor.since_last_boot
      - sensor.date
      - sensor.time
      - sensor.cpu
recorder:
  purge_interval: 1
  purge_keep_days: 3
  exclude:
    domains:
      - automation
      - weblink
      - updater
    entities:
      - sun.sun   # Don't record sun data
      - sensor.last_boot
      - sensor.since_last_boot
      - sensor.date
      - sensor.time
      - sensor.cpu
discovery:
sun:
conversation:
logbook:
frontend:
updater:
#alexa:
#keyboard:

light: !include light.yaml
fan: !include fan.yaml
#chuangmi_ir: !include chuangmi_ir.yaml
# purifier: !include purifier.yaml
device_tracker: !include device_tracker.yaml
sensor: !include sensor.yaml
# media_player: !include media_player.yaml
switch: !include switch.yaml
# notify: !include notify.yaml
group: !include groups.yaml
http: !include http.yaml
zone: !include zones.yaml
#mqtt: !include mqtt.yaml
mqtt:
  broker: 192.168.1.10
shell_command: !include shell_commands.yaml
script: !include scripts.yaml
weblink: !include weblink.yaml
camera: !include camera.yaml
binary_sensor: !include binary_sensor.yaml
telegram_bot:
  platform: polling
  api_key: !secret telegram_apikey
  allowed_chat_ids:
    - !secret telegram_clientid
notify:
  - name: Telegram
    platform: telegram
    api_key: !secret telegram_apikey
    chat_id: !secret telegram_clientid

# to test Telegram: https://home-assistant.io/components/notify/


# Dir List

automation: !include_dir_merge_list automation
scene: !include_dir_merge_list scene
#input_boolean: !include_dir_named input_booleans


####################################################
#                                                  #
#              Input Slider and Boolean            #
#                                                  #
####################################################

# input_select: !include_dir_merge_named input_select
input_number: !include_dir_merge_named input_number

####################################################
#                                                  #
#                     TTS                          #
#                                                  #
####################################################
tts:
  - platform: google
    #cache: true
    #cache_dir: /tts
    #time_memory: 300
    #language: 'en'

####################################################
#                                                  #
#               Panel Iframe                       #
#                                                  #
####################################################
#
#
# Rob
#
#
google_assistant:
  project_id: robhass-711b5
  client_id: LVg3e8nxwa7HuopXJU5fqar2JQseM5d1vkdxGaTnSTnMEiSCCqq4UlS8yi8f8fZIH9U0NeFfMd3uH0N0
  access_token: Wz228Lp3Skpw1ZBkXBDjtJ8BqrHLTBKiT0MsrxT6RtcRtiaMAAgDZZcE9kQOcPh4slIrHH2tc2aXbkpx
  api_key: AIzaSyAN2YaIvVJmiZf-iNPnZ0crd1P5V37i2nk
  exposed_domains:
    - switch
    - light
    - group
    #- cover
    #- media_player
    - fan
    - scene
    #- script
#
# Google Assistant Emulated Hue
emulated_hue:
    #type: alexa
    #host_ip: 192.168.1.10
    listen_port: 8300
    expose_by_default: true
#    exposed_domains:
#      - light
#      - switch
#      - group
#
xiaomi_aqara:
  gateways:
   - mac:
     key: s6ib2p9i7gi9gviz
     # discovery_retry: 10

#robObjects
input_boolean: !include input_boolean.yaml
#
#
# EOF
#
# EOF
