#
#
#Defaults: &defaults
#  Company: foo
#  Item: 123
#Computer:
#  <<: *defaults
#  Price: 3000
#
##- platform: command_line
##  name: Air Purifier Humidity
##  command: miio --control 192.168.1.61 --method get_prop --params '["humidity"]'
##  unit_of_measurement: "%"
##  value_template: '{{ value | replace("INFO","") | replace("Attempting to control 192.168.1.61","") | replace("Got result:","") | replace("[","") | replace("]","") | replace(" ","") }}'
##  scan_interval: 120
##
##- platform: command_line
##  name: Air Purifier PM 2.5
##  command: miio --control 192.168.1.61 --method get_prop --params '["aqi"]'
##  unit_of_measurement: "㎍/m³"
##  value_template: '{{ value | replace("INFO","") | replace("Attempting to control 192.168.1.61","") | replace("Got result:","") | replace("[","") | replace("]","") | replace(" ","") }}'
##  scan_interval: 120
##- platform: command_line
##  name: Air Purifier Power
##  command: miio --control 192.168.1.61 --method get_prop --params '["power"]'
##  value_template: '{{ value | replace("INFO","") | replace("Attempting to control 192.168.1.61","") | replace("Got result:","") | replace("[","") | replace("]","") | replace(" ","") }}'
##  scan_interval: 120
##- platform: command_line
##  name: Air Purifier Mode
##  command: miio --control 192.168.1.61 --method get_prop --params '["mode"]'
##  value_template: '{{ value | replace("INFO","") | replace("Attempting to control 192.168.1.61","") | replace("Got result:","") | replace("[","") | replace("]","") | replace(" ","") }}'
##  scan_interval: 120
#
- platform: command_line
  name: rpi temp
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(2) }}'
#
#
- platform: template
  sensors:
    outsideweather_sensor_battery:
      friendly_name: 'Outside Weather Sensor Battery'
      value_template: '{{ states.sensor.temperature_158d0001563369.attributes.battery_level }}'
      unit_of_measurement: '%'
      icon_template: mdi:battery
    bedroomweather_sensor_battery:
      friendly_name: 'Bedroom Weather Sensor Battery'
      value_template: '{{ states.sensor.humidity_158d0001826d95.attributes.battery_level }}'
      unit_of_measurement: '%'
      icon_template: mdi:battery
    livingroomweather_sensor_battery:
      friendly_name: 'Living Room Weather Sensor Battery'
      value_template: '{{ states.sensor.temperature_158d0001561c0a.attributes.battery_level }}'
      unit_of_measurement: '%'
      icon_template: mdi:battery
#
    frontdooropenclose_sensor_battery:
      friendly_name: 'Front Door Sensor Battery'
      value_template: '{{ states.binary_sensor.switch_158d0001256414.attributes.battery_level }}'
      unit_of_measurement: '%'
      icon_template: mdi:battery
#
    kitchenmotion_sensor_battery:
      friendly_name: 'Kitchen Motion Sensor Battery'
      value_template: '{{ states.binary_sensor.motion_sensor_158d00015b5bab.attributes.battery_level }}'
      unit_of_measurement: '%'
      icon_template: mdi:battery
    livingroommotion_sensor_battery:
      friendly_name: 'Living Room Motion Sensor Battery'
      value_template: '{{ states.binary_sensor.motion_sensor_158d00015a912d.attributes.battery_level }}'
      unit_of_measurement: '%'
      icon_template: mdi:battery
#
    frontdoorswitch_sensor_battery:
      friendly_name: 'Front Door Switch Battery'
      value_template: '{{ states.binary_sensor.switch_158d0001256414.attributes.battery_level }}'
      unit_of_measurement: '%'
      icon_template: mdi:battery
    kitchenswitch_sensor_battery:
      friendly_name: 'Kitchen Switch Battery'
      value_template: '{{ states.binary_sensor.switch_158d00013ecdbf.attributes.battery_level }}'
      unit_of_measurement: '%'
      icon_template: mdi:battery
    bedroomswitch_sensor_battery:
      friendly_name: 'Bedroom Switch Battery'
      value_template: '{{ states.binary_sensor.switch_158d00013ecde4.attributes.battery_level }}'
      unit_of_measurement: '%'
      icon_template: mdi:battery
    bathroomswitch_sensor_battery:
      friendly_name: 'Bathroom Switch Battery'
      value_template: '{{ states.binary_sensor.switch_158d00016bdb80.attributes.battery_level }}'
      unit_of_measurement: '%'
      icon_template: mdi:battery
    sofaswitch_sensor_battery:
      friendly_name: 'Sofa Switch Battery'
      value_template: '{{ states.binary_sensor.switch_158d00016bdbc5.attributes.battery_level }}'
      unit_of_measurement: '%'
      icon_template: mdi:battery
    bedswitch_sensor_battery:
      friendly_name: 'Bed Switch Battery'
      value_template: '{{ states.binary_sensor.switch_158d00016bdbdd.attributes.battery_level }}'
      unit_of_measurement: '%'
      icon_template: mdi:battery
#
    purifier_motor_speed:
      friendly_name: 'Motor Speed'
      unit_of_measurement: 'rpm'
      icon_template: mdi:gauge
      value_template: '{{ states.fan.living_room_air_purifier.attributes.motor_speed | round(0) }}'
#
    purifier_mode:
      friendly_name: 'Mode'
      value_template: '{{ states.fan.living_room_air_purifier.attributes.mode }}'
#    
    purifier_humidity:
      unit_of_measurement: '%'
      friendly_name: 'Humidity'
      icon_template: mdi:water-percent
      value_template: '{{ float(states.fan.living_room_air_purifier.attributes.humidity) }}'
#
    purifier_temperature:
      friendly_name: 'Temperature'
      unit_of_measurement: '°C'
      icon_template: mdi:thermometer
      value_template: '{{ float(states.fan.living_room_air_purifier.attributes.temperature) }}'
#
    purifier_aqi:
      unit_of_measurement: '#'
      friendly_name: 'AQI'
      icon_template: mdi:texture
      value_template: '{{ float(states.fan.living_room_air_purifier.attributes.aqi) }}'
#
#
    purifier_led:
      friendly_name: 'LED'
      value_template: '{{ states.fan.living_room_air_purifier.attributes.led }}'
#
#
#
#- platform: speedtest
#  minute:
#    - 0
#    - 30
#  monitored_conditions:
#    - ping
#    - download
#    - upload
#
#
- platform: darksky
  api_key: !secret DARKSKY_API
  monitored_conditions:
    - summary
    - precip_probability
    - temperature
    - apparent_temperature
    - wind_speed
    - humidity
#
- platform: time_date
  hidden: true
  display_options:
    - 'time'
    - 'date'
#
- platform: cpuspeed
  name: CPU
#
- platform: systemmonitor
  resources:
    - type: memory_free
    - type: memory_use_percent
    - type: processor_use
    - type: since_last_boot
#
#
# EOF
